// editorconfig.rs - EditorConfig export

use std::fs;
use std::path::Path;

use fama_common::{FormatConfig, IndentStyle, LineEnding, QuoteStyle};

/// Export EditorConfig based on FormatConfig defaults
pub fn export() {
	let config = FormatConfig::default();
	export_with_config(&config, Path::new("."));
}

/// Export EditorConfig with a specific config and base path (for testing)
fn export_with_config(config: &FormatConfig, base_path: &Path) {
	// Export rustfmt.toml if Cargo.toml exists
	if base_path.join("Cargo.toml").exists() {
		export_rustfmt(config, base_path);
	}

	// Export analysis_options.yaml if pubspec.yaml exists
	if base_path.join("pubspec.yaml").exists() {
		export_dart(config, base_path);
	}

	let indent_style = match config.indent_style {
		IndentStyle::Tabs => "tab",
		IndentStyle::Spaces => "space",
	};

	let end_of_line = match config.line_ending {
		LineEnding::Lf => "lf",
		LineEnding::Crlf => "crlf",
	};

	let quote_type = match config.quote_style {
		QuoteStyle::Single => "single",
		QuoteStyle::Double => "double",
	};

	let editorconfig = format!(
		r#"# EditorConfig - generated by fama (go-fmt style)
# https://editorconfig.org

root = true

[*]
charset = utf-8
end_of_line = {end_of_line}
insert_final_newline = true
trim_trailing_whitespace = true
indent_style = {indent_style}
indent_size = {indent_size}
tab_width = {indent_size}
max_line_length = {line_width}

# JavaScript/TypeScript
[*.{{js,jsx,ts,tsx,mjs,cjs}}]
quote_type = {quote_type}

# Shell scripts
[*.{{sh,bash,zsh}}]
indent_style = {indent_style}
indent_size = {indent_size}
"#,
		indent_size = config.indent_width,
		line_width = config.line_width
	);

	let editorconfig_path = base_path.join(".editorconfig");
	fs::write(&editorconfig_path, editorconfig)
		.expect("Failed to write .editorconfig");
	println!("Wrote .editorconfig");
}

/// Export analysis_options.yaml based on FormatConfig defaults
fn export_dart(config: &FormatConfig, base_path: &Path) {
	// Dart's analysis_options.yaml formatter section supports:
	//   page_width (Dart 3.7+) and trailing_commas: preserve (Dart 3.8+)
	// trailing_commas only supports "preserve" (keep as-is), which doesn't
	// map to fama's All/None — so we only export page_width.
	let analysis_options = format!(
		r#"# analysis_options.yaml - generated by fama
# https://dart.dev/tools/analysis

formatter:
  page_width: {page_width}
"#,
		page_width = config.line_width,
	);

	let dart_path = base_path.join("analysis_options.yaml");
	fs::write(&dart_path, analysis_options)
		.expect("Failed to write analysis_options.yaml");
	println!("Wrote analysis_options.yaml");
}

/// Export rustfmt.toml based on FormatConfig defaults
fn export_rustfmt(config: &FormatConfig, base_path: &Path) {
	let hard_tabs = matches!(config.indent_style, IndentStyle::Tabs);
	let newline_style = match config.line_ending {
		LineEnding::Lf => "Unix",
		LineEnding::Crlf => "Windows",
	};

	let rustfmt_toml = format!(
		r#"# rustfmt.toml - generated by fama
# https://rust-lang.github.io/rustfmt/

hard_tabs = {hard_tabs}
tab_spaces = {tab_spaces}
max_width = {max_width}
newline_style = "{newline_style}"
"#,
		tab_spaces = config.indent_width,
		max_width = config.line_width,
	);

	let rustfmt_path = base_path.join("rustfmt.toml");
	fs::write(&rustfmt_path, rustfmt_toml)
		.expect("Failed to write rustfmt.toml");
	println!("Wrote rustfmt.toml");
}

#[cfg(test)]
mod tests {
	use super::*;
	use std::fs;
	use tempfile::TempDir;

	#[test]
	fn test_export_creates_editorconfig() {
		let temp_dir = TempDir::new().unwrap();
		let config = FormatConfig::default();

		export_with_config(&config, temp_dir.path());

		let editorconfig_path = temp_dir.path().join(".editorconfig");
		assert!(editorconfig_path.exists());

		let content = fs::read_to_string(&editorconfig_path).unwrap();
		assert!(content.contains("EditorConfig - generated by fama"));
		assert!(content.contains("indent_style = tab"));
		assert!(content.contains("indent_size = 4"));
		assert!(content.contains("max_line_length = 80"));
		assert!(content.contains("end_of_line = lf"));
		assert!(content.contains("quote_type = double"));
	}

	#[test]
	fn test_export_with_cargo_toml_creates_rustfmt() {
		let temp_dir = TempDir::new().unwrap();
		fs::write(temp_dir.path().join("Cargo.toml"), "").unwrap();

		let config = FormatConfig::default();
		export_with_config(&config, temp_dir.path());

		let rustfmt_path = temp_dir.path().join("rustfmt.toml");
		assert!(rustfmt_path.exists());

		let content = fs::read_to_string(&rustfmt_path).unwrap();
		assert!(content.contains("hard_tabs = true"));
		assert!(content.contains("tab_spaces = 4"));
		assert!(content.contains("max_width = 80"));
		assert!(content.contains("newline_style = \"Unix\""));
	}

	#[test]
	fn test_export_with_pubspec_creates_analysis_options() {
		let temp_dir = TempDir::new().unwrap();
		fs::write(temp_dir.path().join("pubspec.yaml"), "").unwrap();

		let config = FormatConfig::default();
		export_with_config(&config, temp_dir.path());

		let dart_path = temp_dir.path().join("analysis_options.yaml");
		assert!(dart_path.exists());

		let content = fs::read_to_string(&dart_path).unwrap();
		assert!(content.contains("page_width: 80"));
	}

	#[test]
	fn test_export_with_all_files() {
		let temp_dir = TempDir::new().unwrap();
		fs::write(temp_dir.path().join("Cargo.toml"), "").unwrap();
		fs::write(temp_dir.path().join("pubspec.yaml"), "").unwrap();

		let config = FormatConfig::default();
		export_with_config(&config, temp_dir.path());

		assert!(temp_dir.path().join(".editorconfig").exists());
		assert!(temp_dir.path().join("rustfmt.toml").exists());
		assert!(temp_dir.path().join("analysis_options.yaml").exists());
	}

	#[test]
	fn test_export_with_spaces_config() {
		let temp_dir = TempDir::new().unwrap();
		fs::write(temp_dir.path().join("Cargo.toml"), "").unwrap();

		let config = FormatConfig {
			indent_style: IndentStyle::Spaces,
			indent_width: 2,
			line_width: 100,
			line_ending: LineEnding::Lf,
			quote_style: QuoteStyle::Single,
			trailing_comma: fama_common::TrailingComma::All,
			semicolons: fama_common::Semicolons::Always,
			bracket_spacing: true,
			brace_style: fama_common::BraceStyle::SameLine,
		};

		export_with_config(&config, temp_dir.path());

		let editorconfig_path = temp_dir.path().join(".editorconfig");
		let content = fs::read_to_string(&editorconfig_path).unwrap();
		assert!(content.contains("indent_style = space"));
		assert!(content.contains("indent_size = 2"));
		assert!(content.contains("max_line_length = 100"));
		assert!(content.contains("quote_type = single"));

		let rustfmt_path = temp_dir.path().join("rustfmt.toml");
		let rustfmt_content = fs::read_to_string(&rustfmt_path).unwrap();
		assert!(rustfmt_content.contains("hard_tabs = false"));
		assert!(rustfmt_content.contains("tab_spaces = 2"));
		assert!(rustfmt_content.contains("max_width = 100"));
	}

	#[test]
	fn test_export_with_crlf() {
		let temp_dir = TempDir::new().unwrap();

		let config = FormatConfig {
			indent_style: IndentStyle::Tabs,
			indent_width: 4,
			line_width: 80,
			line_ending: LineEnding::Crlf,
			quote_style: QuoteStyle::Double,
			trailing_comma: fama_common::TrailingComma::All,
			semicolons: fama_common::Semicolons::Always,
			bracket_spacing: true,
			brace_style: fama_common::BraceStyle::SameLine,
		};

		export_with_config(&config, temp_dir.path());

		let editorconfig_path = temp_dir.path().join(".editorconfig");
		let content = fs::read_to_string(&editorconfig_path).unwrap();
		assert!(content.contains("end_of_line = crlf"));
	}

	#[test]
	fn test_export_without_extra_files() {
		let temp_dir = TempDir::new().unwrap();
		// No Cargo.toml or pubspec.yaml

		let config = FormatConfig::default();
		export_with_config(&config, temp_dir.path());

		assert!(temp_dir.path().join(".editorconfig").exists());
		assert!(!temp_dir.path().join("rustfmt.toml").exists());
		assert!(!temp_dir.path().join("analysis_options.yaml").exists());
	}
}
