// editorconfig.rs - EditorConfig export

use fama_common::{FormatConfig, IndentStyle, LineEnding, QuoteStyle};

/// Export EditorConfig based on FormatConfig defaults
pub fn export() {
    let config = FormatConfig::default();

    let indent_style = match config.indent_style {
        IndentStyle::Tabs => "tab",
        IndentStyle::Spaces => "space",
    };

    let end_of_line = match config.line_ending {
        LineEnding::Lf => "lf",
        LineEnding::Crlf => "crlf",
    };

    let quote_type = match config.quote_style {
        QuoteStyle::Single => "single",
        QuoteStyle::Double => "double",
    };

    let editorconfig = format!(
        r#"# EditorConfig - generated by fama (go-fmt style)
# https://editorconfig.org

root = true

[*]
charset = utf-8
end_of_line = {end_of_line}
insert_final_newline = true
trim_trailing_whitespace = true
indent_style = {indent_style}
indent_size = {indent_size}
tab_width = {indent_size}
max_line_length = {line_width}

# JavaScript/TypeScript
[*.{{js,jsx,ts,tsx,mjs,cjs}}]
quote_type = {quote_type}

# Shell scripts
[*.{{sh,bash,zsh}}]
indent_style = {indent_style}
indent_size = {indent_size}
"#,
        indent_size = config.indent_width,
        line_width = config.line_width
    );

    println!("{}", editorconfig);
}
