// editorconfig.rs - EditorConfig export

use std::fs;
use std::path::Path;

use fama_common::{FormatConfig, IndentStyle, LineEnding, QuoteStyle};

/// Export EditorConfig based on FormatConfig defaults
pub fn export() {
	let config = FormatConfig::default();

	// Export rustfmt.toml if Cargo.toml exists
	if Path::new("Cargo.toml").exists() {
		export_rustfmt(&config);
	}

	// Export analysis_options.yaml if pubspec.yaml exists
	if Path::new("pubspec.yaml").exists() {
		export_dart(&config);
	}

	let indent_style = match config.indent_style {
		IndentStyle::Tabs => "tab",
		IndentStyle::Spaces => "space",
	};

	let end_of_line = match config.line_ending {
		LineEnding::Lf => "lf",
		LineEnding::Crlf => "crlf",
	};

	let quote_type = match config.quote_style {
		QuoteStyle::Single => "single",
		QuoteStyle::Double => "double",
	};

	let editorconfig = format!(
		r#"# EditorConfig - generated by fama (go-fmt style)
# https://editorconfig.org

root = true

[*]
charset = utf-8
end_of_line = {end_of_line}
insert_final_newline = true
trim_trailing_whitespace = true
indent_style = {indent_style}
indent_size = {indent_size}
tab_width = {indent_size}
max_line_length = {line_width}

# JavaScript/TypeScript
[*.{{js,jsx,ts,tsx,mjs,cjs}}]
quote_type = {quote_type}

# Shell scripts
[*.{{sh,bash,zsh}}]
indent_style = {indent_style}
indent_size = {indent_size}
"#,
		indent_size = config.indent_width,
		line_width = config.line_width
	);

	fs::write(".editorconfig", editorconfig)
		.expect("Failed to write .editorconfig");
	println!("Wrote .editorconfig");
}

/// Export analysis_options.yaml based on FormatConfig defaults
fn export_dart(config: &FormatConfig) {
	// Dart's analysis_options.yaml formatter section supports:
	//   page_width (Dart 3.7+) and trailing_commas: preserve (Dart 3.8+)
	// trailing_commas only supports "preserve" (keep as-is), which doesn't
	// map to fama's All/None — so we only export page_width.
	let analysis_options = format!(
		r#"# analysis_options.yaml - generated by fama
# https://dart.dev/tools/analysis

formatter:
  page_width: {page_width}
"#,
		page_width = config.line_width,
	);

	fs::write("analysis_options.yaml", analysis_options)
		.expect("Failed to write analysis_options.yaml");
	println!("Wrote analysis_options.yaml");
}

/// Export rustfmt.toml based on FormatConfig defaults
fn export_rustfmt(config: &FormatConfig) {
	let hard_tabs = matches!(config.indent_style, IndentStyle::Tabs);
	let newline_style = match config.line_ending {
		LineEnding::Lf => "Unix",
		LineEnding::Crlf => "Windows",
	};

	let rustfmt_toml = format!(
		r#"# rustfmt.toml - generated by fama
# https://rust-lang.github.io/rustfmt/

hard_tabs = {hard_tabs}
tab_spaces = {tab_spaces}
max_width = {max_width}
newline_style = "{newline_style}"
"#,
		tab_spaces = config.indent_width,
		max_width = config.line_width,
	);

	fs::write("rustfmt.toml", rustfmt_toml)
		.expect("Failed to write rustfmt.toml");
	println!("Wrote rustfmt.toml");
}
